# Ejercicios Basicos de Numpy
### https://gemini.google.com/u/1/app/393a7c30921eff1b?hl=es

In [215]:
## importamos las librerias

import numpy as np

# Ejercicio 1

## Parte 1
### Creando e imprimiendo arrays:
- Crea un array unidimensional con los números del 1 al 5.
- Imprime el array completo.
- Crea un array bidimensional de 2 filas y 3 columnas con valores 0, 1 y 2.
- Imprime el array completo.
- 

In [216]:
"""
- Crea un array unidimensional con los números del 1 al 5.
- Imprime el array completo.
  """
undimensional = np.array([1,2,3,4,5])
print(undimensional)

[1 2 3 4 5]


In [217]:
"""
- Crea un array bidimensional de 2 filas y 3 columnas con valores 0, 1 y 2.
- Imprime el array completo.
  """
  
bidimensional = np.array([[0,1,2],[0,1,2]])

## Parte 2
### Obteniendo información de arrays:
- Crea un array de 10 números aleatorios entre 0 y 100.
- Muestra la cantidad de elementos del array.
- Obtén el tipo de datos del array.
- Verifica si todos los elementos del array son iguales.



In [218]:
#Crea un array de 10 números aleatorios entre 0 y 100.

array = np.random.randint(0,101,size= 10)
print(array)

[ 4 66 40 74 75 13 83 81  5 53]


In [219]:
#Muestra la cantidad de elementos del array.
print(len(array)) ## para saber su longitud

10


In [220]:
#Obtén el tipo de datos del array.
print(type(array))

<class 'numpy.ndarray'>


In [221]:
#Verifica si todos los elementos del array son iguales.
hola = np.array([1,1,1])
if np.all(array == array[0]):
  print("son iguales")
else:
  print("no son iguales")
  

no son iguales


## Part 3
###  Operaciones básicas con arrays:
- Crea dos arrays unidimensionales del mismo tamaño con valores enteros.
- Suma los dos arrays elemento a elemento.
- Resta el segundo array del primer array elemento a elemento.
- Multiplica cada elemento del primer array por el elemento correspondiente del segundo array.
- Divide cada elemento del primer array por el elemento correspondiente del segundo array (considerando la división flotante).

In [222]:
# Crea dos arrays unidimensionales del mismo tamaño con valores enteros.

array1 = np.random.randint(10,size=4)
array2 = np.random.randint(10,size=4)
print(array1)
print(array2)

[6 8 2 9]
[9 6 3 7]


In [223]:
#Suma los dos arrays elemento a elemento.
print(array1 + array2)
print([array1[0] + array2[0], array1[1] + array2[1], array1[2]+ array2[2],array1[3] + array2[3]])

[15 14  5 16]
[15, 14, 5, 16]


In [224]:
#Resta el segundo array del primer array elemento a elemento.
print(array1 - array2)
print([array1[0] - array2[0], array1[1] - array2[1], array1[2]- array2[2],array1[3] - array2[3]])

[-3  2 -1  2]
[-3, 2, -1, 2]


In [225]:
#Multiplica cada elemento del primer array por el elemento correspondiente del segundo array.
print(array1 * array2)
print([array1[0] * array2[0], array1[1] * array2[1], array1[2]* array2[2],array1[3] * array2[3]])

[54 48  6 63]
[54, 48, 6, 63]


In [226]:
#Divide cada elemento del primer array por el elemento correspondiente del segundo array (considerando la división flotante).
print(array1 / array2)
print([array1[0] / array2[0], array1[1] / array2[1], array1[2]/ array2[2],array1[3] / array2[3]])

[0.66666667 1.33333333 0.66666667 1.28571429]
[0.6666666666666666, 1.3333333333333333, 0.6666666666666666, 1.2857142857142858]


## Parte 4
### Seleccionando elementos de arrays:
-  Crea un array de 10 números aleatorios entre 0 y 100.
-  Muestra el primer y último elemento del array.
-  Muestra los elementos del array que son mayores a 50.
-  Muestra los elementos del array en las posiciones pares.


In [227]:
#Crea un array de 10 números aleatorios entre 0 y 100.
array_difficult = np.random.randint(0,101,size= 10)
print(f"El array completo es: {array_difficult}")


El array completo es: [82 17 19 32  4 15 36 44 69 95]


In [228]:
#Muestra el primer y último elemento del array.
print(f"The first value is: {array_difficult[0]}")
print(f"The first value is: {array_difficult[9]}")


The first value is: 82
The first value is: 95


In [229]:
#Muestra los elementos del array que son mayores a 50.
new_array_difficult = []
for i in array_difficult:
  if i >50:
    new_array_difficult.append(i)
    
print(new_array_difficult)
  

[82, 69, 95]


In [230]:
# Muestra los elementos del array en las posiciones pares.
for i in range(len(array_difficult)):
  if i %2 ==0 and i != 0:
    print(array_difficult[i])


hola =[2,4,6,8]

for i in hola:
  print(array_difficult[i])

19
4
36
69
19
4
36
69


## Parte 5
### Creando arrays a partir de otras estructuras:

Crea una lista de 5 nombres de ciudades.

Convierte la lista en un array NumPy.

Crea un array de 10 números decimales.

Redondea los números del array a dos decimales y crea un nuevo array con los valores redondeados.

In [231]:
# Crea una lista de 5 nombres de ciudades.
cities_name = ["Madrid","Barcelona", "Montevideo","Nueva York", "Bogota"]

In [232]:
#Convierte la lista en un array NumPy.
cities = np.array(cities_name)
print(f"El array: {cities} es de tipo: {type(cities)}")

El array: ['Madrid' 'Barcelona' 'Montevideo' 'Nueva York' 'Bogota'] es de tipo: <class 'numpy.ndarray'>


In [233]:
#Crea un array de 10 números decimales.
decimal_array = np.random.rand(10) * 100
print(decimal_array)


[19.68297979 13.0624186  55.68946307 56.83067296 68.87696089 45.42576851
  2.88880672 63.61481956 88.41145225 15.6074465 ]


In [234]:
# Redondea los números del array a dos decimales y crea un nuevo array con los valores redondeados.
round_array = np.round(decimal_array,decimals=2)

print(round_array)

[19.68 13.06 55.69 56.83 68.88 45.43  2.89 63.61 88.41 15.61]


# Ejercicio 2

## Parte 1

### Estadisticas con Numpy


In [235]:
## Crea un array con datos de ventas de un negocio durante un mes.
ventas = np.array([2,42,424,4,3])

In [236]:
#calcula la media, la mediana y la desviación estándar de las ventas.

mean = np.mean(ventas)
print(f"The mean will be: {mean}")

median = np.median(ventas)
print(f"The median will be: {median}")

var = np.var(ventas)

print(f"The standard desviation will be: {var*0.5}")


The mean will be: 95.0
The median will be: 4.0
The standard desviation will be: 13644.4
