# Ejercicios Basicos de Numpy
### https://gemini.google.com/u/1/app/393a7c30921eff1b?hl=es

In [2]:
## importamos las librerias

import numpy as np

# Ejercicio 1

## Parte 1
### Creando e imprimiendo arrays:
- Crea un array unidimensional con los números del 1 al 5.
- Imprime el array completo.
- Crea un array bidimensional de 2 filas y 3 columnas con valores 0, 1 y 2.
- Imprime el array completo.
- 

In [3]:
"""
- Crea un array unidimensional con los números del 1 al 5.
- Imprime el array completo.
  """
undimensional = np.array([1,2,3,4,5])
print(undimensional)

[1 2 3 4 5]


In [4]:
"""
- Crea un array bidimensional de 2 filas y 3 columnas con valores 0, 1 y 2.
- Imprime el array completo.
  """
  
bidimensional = np.array([[0,1,2],[0,1,2]])

## Parte 2
### Obteniendo información de arrays:
- Crea un array de 10 números aleatorios entre 0 y 100.
- Muestra la cantidad de elementos del array.
- Obtén el tipo de datos del array.
- Verifica si todos los elementos del array son iguales.



In [5]:
#Crea un array de 10 números aleatorios entre 0 y 100.

array = np.random.randint(0,101,size= 10)
print(array)

[88 55 92 86 90 95 52 33 77 69]


In [6]:
#Muestra la cantidad de elementos del array.
print(len(array)) ## para saber su longitud

10


In [7]:
#Obtén el tipo de datos del array.
print(type(array))

<class 'numpy.ndarray'>


In [8]:
#Verifica si todos los elementos del array son iguales.
hola = np.array([1,1,1])
if np.all(array == array[0]):
  print("son iguales")
else:
  print("no son iguales")
  

no son iguales


## Part 3
###  Operaciones básicas con arrays:
- Crea dos arrays unidimensionales del mismo tamaño con valores enteros.
- Suma los dos arrays elemento a elemento.
- Resta el segundo array del primer array elemento a elemento.
- Multiplica cada elemento del primer array por el elemento correspondiente del segundo array.
- Divide cada elemento del primer array por el elemento correspondiente del segundo array (considerando la división flotante).

In [9]:
# Crea dos arrays unidimensionales del mismo tamaño con valores enteros.

array1 = np.random.randint(10,size=4)
array2 = np.random.randint(10,size=4)
print(array1)
print(array2)

[1 3 2 2]
[6 1 1 5]


In [10]:
#Suma los dos arrays elemento a elemento.
print(array1 + array2)
print([array1[0] + array2[0], array1[1] + array2[1], array1[2]+ array2[2],array1[3] + array2[3]])

[7 4 3 7]
[7, 4, 3, 7]


In [11]:
#Resta el segundo array del primer array elemento a elemento.
print(array1 - array2)
print([array1[0] - array2[0], array1[1] - array2[1], array1[2]- array2[2],array1[3] - array2[3]])

[-5  2  1 -3]
[-5, 2, 1, -3]


In [12]:
#Multiplica cada elemento del primer array por el elemento correspondiente del segundo array.
print(array1 * array2)
print([array1[0] * array2[0], array1[1] * array2[1], array1[2]* array2[2],array1[3] * array2[3]])

[ 6  3  2 10]
[6, 3, 2, 10]


In [13]:
#Divide cada elemento del primer array por el elemento correspondiente del segundo array (considerando la división flotante).
print(array1 / array2)
print([array1[0] / array2[0], array1[1] / array2[1], array1[2]/ array2[2],array1[3] / array2[3]])

[0.16666667 3.         2.         0.4       ]
[0.16666666666666666, 3.0, 2.0, 0.4]


## Parte 4
### Seleccionando elementos de arrays:
-  Crea un array de 10 números aleatorios entre 0 y 100.
-  Muestra el primer y último elemento del array.
-  Muestra los elementos del array que son mayores a 50.
-  Muestra los elementos del array en las posiciones pares.


In [14]:
#Crea un array de 10 números aleatorios entre 0 y 100.
array_difficult = np.random.randint(0,101,size= 10)
print(f"El array completo es: {array_difficult}")


El array completo es: [66 20 81 14 75 21 16 94 84 85]


In [15]:
#Muestra el primer y último elemento del array.
print(f"The first value is: {array_difficult[0]}")
print(f"The first value is: {array_difficult[9]}")


The first value is: 66
The first value is: 85


In [16]:
#Muestra los elementos del array que son mayores a 50.
new_array_difficult = []
for i in array_difficult:
  if i >50:
    new_array_difficult.append(i)
    
print(new_array_difficult)
  

[66, 81, 75, 94, 84, 85]


In [17]:
# Muestra los elementos del array en las posiciones pares.
for i in range(len(array_difficult)):
  if i %2 ==0 and i != 0:
    print(array_difficult[i])


hola =[2,4,6,8]

for i in hola:
  print(array_difficult[i])

81
75
16
84
81
75
16
84


## Parte 5
### Creando arrays a partir de otras estructuras:

Crea una lista de 5 nombres de ciudades.

Convierte la lista en un array NumPy.

Crea un array de 10 números decimales.

Redondea los números del array a dos decimales y crea un nuevo array con los valores redondeados.

In [18]:
# Crea una lista de 5 nombres de ciudades.
cities_name = ["Madrid","Barcelona", "Montevideo","Nueva York", "Bogota"]

In [19]:
#Convierte la lista en un array NumPy.
cities = np.array(cities_name)
print(f"El array: {cities} es de tipo: {type(cities)}")

El array: ['Madrid' 'Barcelona' 'Montevideo' 'Nueva York' 'Bogota'] es de tipo: <class 'numpy.ndarray'>


In [20]:
#Crea un array de 10 números decimales.
decimal_array = np.random.rand(10) * 100
print(decimal_array)


[29.65818539 20.06948076 73.40735298 87.38238445 56.11455282 74.56270004
 54.05756287 29.7879482  13.39298724 78.55566286]


In [21]:
# Redondea los números del array a dos decimales y crea un nuevo array con los valores redondeados.
round_array = np.round(decimal_array,decimals=2)

print(round_array)

[29.66 20.07 73.41 87.38 56.11 74.56 54.06 29.79 13.39 78.56]


# Ejercicio 2

## Parte 1

### Estadisticas con Numpy


In [22]:
## Crea un array con datos de ventas de un negocio durante un mes.
ventas = np.array([2,42,424,4,3])

In [23]:
#calcula la media, la mediana y la desviación estándar de las ventas.

mean = np.mean(ventas)
print(f"The mean will be: {mean}")

median = np.median(ventas)
print(f"The median will be: {median}")

var = np.var(ventas)

print(f"The standard desviation will be: {var*0.5}")


The mean will be: 95.0
The median will be: 4.0
The standard desviation will be: 13644.4


In [39]:
#Identifica el día del mes con mayor volumen de ventas y el día con menor volumen de ventas.

dia_con_mayor_volumen = np.where(ventas == int(max(ventas)))[0][0]
print(dia_con_mayor_volumen)
dia_con_menor_volumen = np.where(ventas == int(min(ventas)))[0][0]
if dia_con_menor_volumen ==0:
  print(1)
  


2
1


In [45]:
#Calcula el rango intercuartílico (IQR) de las ventas.


Q3 = np.quantile(ventas, 0.75)
Q1 = np.quantile(ventas, 0.25)
IQR = Q3 - Q1
print(f"El rango intercuartilico es: {IQR}")

El rango intercuartilico es: 39.0


## Parte 2
###  Manipulación de arrays:

In [53]:
# Crea un array bidimensional con datos de temperatura y humedad para diferentes ciudades.

temp_hume = np.array([[20,34],[13,16]])
temp_hume.ndim

2

In [56]:
#Obtén un nuevo array que contenga solo las temperaturas de las ciudades.

temperature = temp_hume[0]
print(temperature)

[20 34]


In [63]:
# Ordena el array original por temperatura de forma ascendente y descendente.

ordered_by_temperature_increase = sorted(temp_hume, key=lambda x:x[0],reverse=False)

print(ordered_by_temperature_increase[0][0]) #! Todavia no funciona

13
