In [1]:
import numpy as np # We import numpy

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([[[2.5,5.4, 16.2], [9.0, 12.3, 4.5],[3.5,63.5,25.5]]])
print(b)  # it a matrix with three dimensions using floats

[[[ 2.5  5.4 16.2]
  [ 9.  12.3  4.5]
  [ 3.5 63.5 25.5]]]


In [4]:
c = np.array([[2, 5, 2],[3, 5, 6]], dtype= 'int16') # We can type it and put the pre size
print(c)

[[2 5 2]
 [3 5 6]]


In [5]:
# Get the number of dimension
b.ndim # to know the number of dimensions

3

In [6]:
# Get the shape
b.shape # Ir return the number of lines and columns


(1, 3, 3)

In [7]:
# get the type and the size
b.dtype # To know the data type

dtype('float64')

In [8]:
c.dtype

dtype('int16')

In [9]:
# Get size
a.itemsize # ir return 2 bytes, because 16 bits are 2 bytes

4

In [10]:
# get the numbers of element
a.size

3

In [11]:
# get the total size
a.nbytes # is intmsize times size

12

# Accessing/Changing Specific elements, rows, columns, etc.

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8, 9, 10, 11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
# get specific element[r, c]  where r is rows and c is columns

print(a[0,2])

3


In [14]:
# get specific row
print(a[0, ]) # All the row

[1 2 3 4 5 6 7]


In [15]:
# get specific column
print(a[:,0 ]) # All a column

[1 8]


In [16]:
# Getting a little more fancy[startindex:endindex:stepsize]

print(a[0, 1:6:1])# Star in row 0 in column 1 to column 6   going a number into a number

[2 3 4 5 6]


In [17]:
## to add
a[1,0]= 20 # Add 20 in row 0 and column 0
print(a)

a[:, 2]= [1,2]

[[ 1  2  3  4  5  6  7]
 [20  9 10 11 12 13 14]]


In [18]:
b = np.array([[[1,2 ],[3, 4],[5,6],[7, 8]]])
b

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [19]:
# Get specific element(work outside in)
b[0,1 ,1 ] # TODO I don't know why xd

4

In [20]:
# replace
b[:,1,:] = [[9, 9]] # replacing a matrix
b

array([[[1, 2],
        [9, 9],
        [5, 6],
        [7, 8]]])

# Initializing Different Types of Arrays

In [21]:
# All 0s matrix
np.zeros(4) # A array with just zeros
np.zeros((2*2)) # an array with 4 zeros


np.zeros((2, 3, 3, 2)) # matrix with 6 dimensions

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [22]:
# All 1s matrix
np.ones(4) # array with just 1s

np.ones((3,3)) # a matrix

np.ones((3,3), dtype= "int32") # a matrix but specific using int32


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
# Any other number
np.full((2,2), 99) # we put any number  in the first argument the times or the model of the matrix and the second argument is what number dp you like to use

array([[99, 99],
       [99, 99]])

In [24]:
# Any other number(full_like)
np.full_like(a, 4)  # replacing all the values from a 

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
# Random decimal numbers

np.random.rand(4,2)


array([[0.38963619, 0.75941664],
       [0.02906326, 0.64115658],
       [0.28694786, 0.39066997],
       [0.17613233, 0.85545979]])

In [26]:
# Random Integer values
np.random.randint(7)

np.random.randint(7, size=(3,3))

array([[6, 1, 0],
       [1, 2, 4],
       [3, 0, 0]])

In [27]:
#The identify matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
arr = np.array([[1, 2, 3]])
rl = np.repeat(arr, 3, axis=0)
rl

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [29]:
output = np.ones((5,5))

print(output)

z = np.zeros((3, 3))

z[1, 1] = 9
print(z)
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays

In [30]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


# Mathematics

In [31]:
a = np.array([1,2, 3, 4])
print(a)

[1 2 3 4]


In [32]:
a + 2

array([3, 4, 5, 6])

In [33]:
a  - 2

array([-1,  0,  1,  2])

In [34]:
a *2

array([2, 4, 6, 8])

In [35]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [36]:
b = np.array([1, 0, 1, 0])

a + b


array([2, 2, 4, 4])

In [37]:
# Take the sin
np.sin(a)
np.cos(a)
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

## Linear Algebra

In [38]:
a = np.ones((2,3))
print(a)
b = np.full((3, 2), 2)
print(b)

# times two matrices

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [39]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [40]:
stats = np.array([[1, 2, 3],[4, 5, 6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
# To get the minimus
np.min(stats)

1

In [42]:
# To get the max
np.max(stats)

6

In [43]:
# To sum or add
np.sum(stats)

21

# Reorganizing Arrays


In [44]:
before = np.array([[1,2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape(8,1)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [45]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
# Horizontal stack
h1 = np.array((2, 4))
h2 = np.array((2, 2))

np.hstack((h1, h2))

array([2, 4, 2, 2])

## Miscellaneous


#### Load Data from FIle

In [47]:
file_data =np.genfromtxt("data.txt", delimiter= ",") #The separate by comas
file_data


array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

#### Boolean Masking and Advanced Indexing

In [48]:
file_data > 50 # Return  True if the number of lines in 'file_data' is greater than 50, False other case

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [49]:
file_data[file_data > 50]  # Return the number which are  greater than 50

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [50]:
# We can filter it as  a list

a = np.array([1, 2, 3, 4, 5, 6, 7,8, 9])

a[[0, 1,8 ]] # It works as a normal list to take out a element of a list using its index


array([1, 2, 9])

In [51]:
np.any(file_data > 50, axis=0) #TODO : check if this is correct

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [52]:
### We can do multiply conditions

((file_data > 50) & (file_data < 100)) # We use logic symbols like | &  ~, etc

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])