# Ejercicios Basicos de Numpy
### https://gemini.google.com/u/1/app/393a7c30921eff1b?hl=es

In [98]:
## importamos las librerias

import numpy as np

# Parte 1
### Creando e imprimiendo arrays:
- Crea un array unidimensional con los números del 1 al 5.
- Imprime el array completo.
- Crea un array bidimensional de 2 filas y 3 columnas con valores 0, 1 y 2.
- Imprime el array completo.
- 

In [99]:
"""
- Crea un array unidimensional con los números del 1 al 5.
- Imprime el array completo.
  """
undimensional = np.array([1,2,3,4,5])
print(undimensional)

[1 2 3 4 5]


In [100]:
"""
- Crea un array bidimensional de 2 filas y 3 columnas con valores 0, 1 y 2.
- Imprime el array completo.
  """
  
bidimensional = np.array([[0,1,2],[0,1,2]])

# Parte 2
### Obteniendo información de arrays:
- Crea un array de 10 números aleatorios entre 0 y 100.
- Muestra la cantidad de elementos del array.
- Obtén el tipo de datos del array.
- Verifica si todos los elementos del array son iguales.



In [101]:
#Crea un array de 10 números aleatorios entre 0 y 100.

array = np.random.randint(0,101,size= 10)
print(array)

[ 0 54 36 10 36 70 80 63 36 36]


In [102]:
#Muestra la cantidad de elementos del array.
print(len(array)) ## para saber su longitud

10


In [103]:
#Obtén el tipo de datos del array.
print(type(array))

<class 'numpy.ndarray'>


In [104]:
#Verifica si todos los elementos del array son iguales.
hola = np.array([1,1,1])
if np.all(array == array[0]):
  print("son iguales")
else:
  print("no son iguales")
  

no son iguales


# Part 3
###  Operaciones básicas con arrays:
- Crea dos arrays unidimensionales del mismo tamaño con valores enteros.
- Suma los dos arrays elemento a elemento.
- Resta el segundo array del primer array elemento a elemento.
- Multiplica cada elemento del primer array por el elemento correspondiente del segundo array.
- Divide cada elemento del primer array por el elemento correspondiente del segundo array (considerando la división flotante).

In [105]:
# Crea dos arrays unidimensionales del mismo tamaño con valores enteros.

array1 = np.random.randint(10,size=4)
array2 = np.random.randint(10,size=4)
print(array1)
print(array2)

[7 8 9 9]
[4 7 0 4]


In [106]:
#Suma los dos arrays elemento a elemento.
print(array1 + array2)
print([array1[0] + array2[0], array1[1] + array2[1], array1[2]+ array2[2],array1[3] + array2[3]])

[11 15  9 13]
[11, 15, 9, 13]


In [107]:
#Resta el segundo array del primer array elemento a elemento.
print(array1 - array2)
print([array1[0] - array2[0], array1[1] - array2[1], array1[2]- array2[2],array1[3] - array2[3]])

[3 1 9 5]
[3, 1, 9, 5]


In [108]:
#Multiplica cada elemento del primer array por el elemento correspondiente del segundo array.
print(array1 * array2)
print([array1[0] * array2[0], array1[1] * array2[1], array1[2]* array2[2],array1[3] * array2[3]])

[28 56  0 36]
[28, 56, 0, 36]


In [109]:
#Divide cada elemento del primer array por el elemento correspondiente del segundo array (considerando la división flotante).
print(array1 / array2)
print([array1[0] / array2[0], array1[1] / array2[1], array1[2]/ array2[2],array1[3] / array2[3]])

[1.75       1.14285714        inf 2.25      ]
[1.75, 1.1428571428571428, inf, 2.25]


C:\Users\santi\AppData\Local\Temp\ipykernel_21860\229368744.py:2: RuntimeWarning: divide by zero encountered in divide
  print(array1 / array2)
C:\Users\santi\AppData\Local\Temp\ipykernel_21860\229368744.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  print([array1[0] / array2[0], array1[1] / array2[1], array1[2]/ array2[2],array1[3] / array2[3]])


# Parte 4
### Seleccionando elementos de arrays:
-  Crea un array de 10 números aleatorios entre 0 y 100.
-  Muestra el primer y último elemento del array.
-  Muestra los elementos del array que son mayores a 50.
-  Muestra los elementos del array en las posiciones pares.


In [110]:
#Crea un array de 10 números aleatorios entre 0 y 100.
array_difficult = np.random.randint(0,101,size= 10)
print(f"El array completo es: {array_difficult}")


El array completo es: [ 7 74 47 17 94 94 75 16 38 47]


In [111]:
#Muestra el primer y último elemento del array.
print(f"The first value is: {array_difficult[0]}")
print(f"The first value is: {array_difficult[9]}")


The first value is: 7
The first value is: 47


In [112]:
#Muestra los elementos del array que son mayores a 50.
new_array_difficult = []
for i in array_difficult:
  if i >50:
    new_array_difficult.append(i)
    
print(new_array_difficult)
  

[74, 94, 94, 75]


In [128]:
# Muestra los elementos del array en las posiciones pares.
for i in range(len(array_difficult)):
  if i %2 ==0 and i != 0:
    print(array_difficult[i])


hola =[2,4,6,8]

for i in hola:
  print(array_difficult[i])

47
94
75
38
47
94
75
38
Hola es 3 y coso es 2
Hola es: 3 y coso es: 2
